# Generated by Django 3.2.12 on 2023-01-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='initiators',
            new_name='initiator',
        ),
    ]
